<!-- Automatically generated by 'glameow' -->
<template>
<el-row>
	<el-row>
		<el-col :span="24" class="header" style="height:60px;line-height:60px;background:blue;color:#fff;">
			<el-col :span="10" class="logo" style="width:230px;height:60px;font-size:22px;padding-left:20px;padding-right:20px;border-color:rgba(238,241,146,0.3);border-right-width:1px;border-right-style:solid;"><span style="color:#fff;">glameow</span></el-col>
			<el-col :span="4" :offset="10" class="userinfo" style="text-align:right;padding-right:35px;float:right;"><span class="userinfo-inner" style="color:#fff;">Ajain<img class="userinfo-inner" src="https://avatars0.githubusercontent.com/u/1182600?s=40"
					  style="width:40px;height:40px;border-radius:20px;margin:10px 0px 10px 10px;float:right;"></span></el-col>
		</el-col>
	</el-row>
</el-row>
</template>

<script>
export default {
	name: "Header",

	data: function () {
		return {}
	}
}
</script>
