<!-- Automatically generated by 'glameow' -->
<template>
<el-container>
	<el-header>
		<el-col :gutter="10">
			<el-row :xs="12" :sm="8" :md="4" :lg="3" :xl="1">
			</el-row>
		</el-col>
	</el-header>
	<el-main :gutter="10" :style="{&quot;backgroundColor&quot;:&quot;#efeff4&quot;}">
		<el-row :xs="12" :sm="8" :md="4" :lg="3" :xl="1">
			<el-button element="primary">Generated Button</el-button>
		</el-row>
	</el-main>
</el-container>
</template>

<script>
export default {
	name: "Home",
	meta() {
		return {
			title: "Home",
			description: "This is the meta description for the home page"
		}
	},
	data: function () {
		return {
			
		}
	}
}
</script>
