<!-- Automatically generated by 'glameow' -->
<template>
<div style="background-color:#efeff4;">
	<div>
		<el-row :gutter="10">
			<el-col :xs="12" :sm="8" :md="4" :lg="3" :xl="1">
				<el-input v-model="inputValue" placeholder="Please input"></el-input>
			</el-col>
		</el-row>
	</div>
	<el-row :gutter="10">
		<el-col :xs="12" :sm="8" :md="4" :lg="3" :xl="1">
			<el-button element="primary">Button</el-button>
		</el-col>
	</el-row>
</div>
</template>

<script>
export default {
	name: "Home",
	meta() {
		return {
			title: "Home",
			description: "This is the meta description for the home page"
		}
	},
	data: function () {
		return {
			"global": {
				"title": "text"
			},
			"inputValue": "That is cool!"
		}
	}
}
</script>
