<!-- Automatically generated by 'glameow' -->
<template>
<div class="page" style="background-color:#efeff4;height:calc(100vh - 60px);">
	<div>
		<el-row :gutter="10">
			<el-col :span="24">
				<h2 style="padding:30px 0;">{{heading}}</h2>
			</el-col>
		</el-row>
	</div>
	<el-row :gutter="10">
		<el-col :span="24"><img src="https://pa1.narvii.com/6773/ecc0241941f28cf3bda17945d74da1dc6e1b7804_hq.gif" height="400"></el-col>
	</el-row>
</div>
</template>

<script>
export default {
	name: "Home",
	meta() {
		return {
			title: "Home",
			description: "This is the meta description for the home page"
		}
	},
	data: function () {
		return {
			"heading": "This page was generated by awesome glameow! purrr!!"
		}
	}
}
</script>
